# Generated by Django 6.0.6 on 2026-09-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cultura')),
                ('largura', models.FloatField(verbose_name='Largura (m)')),
                ('comprimento', models.FloatField(verbose_name='Comprimento (m)')),
                ('ruas', models.PositiveIntegerField(verbose_name='Quantidade de ruas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'ordering': ['nome'],
            },
        ),
    ]
